---
- hosts: webservers
  remote_user: jenkins
  tasks:
     
  - name: Remove Cloud security client container ...
    shell: docker rm -f cloud.security.client
    ignore_errors: yes

  - name: Remove Cloud security client image ...
    shell: docker rmi -f cloud.security.client
    ignore_errors: yes
  
  - name: Create temp folder ...
    shell: mkdir /home/jenkins/cloud.security.client.tmp && mkdir /home/jenkins/cloud.security.client.tmp/logs
    ignore_errors: yes
    
  - name: Copy Cloud security client jar ...
    copy: src=cloud.security.client-1.0.jar dest=/home/jenkins/cloud.security.client.tmp
  
  - name: Copy Cloud security client Dockerfile ...
    copy: src=Dockerfile dest=/home/jenkins/cloud.security.client.tmp
  
  - name: Build Cloud security client image ...
    shell: cd /home/jenkins/cloud.security.client.tmp && docker build -t cloud.security.client .
  
  - name: Run Cloud security client containers...
    shell: docker run -d --name cloud.security.client -p 3000:3000 -e CLOUD.CONFIG.ROOT.PATH=/cloud.config/test/cloud.security.client/ -e CLOUD.CONFIG.SERVICE.URL=http://10.39.101.226:7098/GetConfigFile -e CLOUD.CONFIG.SERVICE.AUTH.CODE=config.auth.code:001 --restart=always -v /logs:/logs cloud.security.client
    
 
 